=== mithunmo/phpsample/data/dtds/bootstrapConfig.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bootstrap ( application, filename, fileLocation, classes ) >

<!ELEMENT application ( #PCDATA ) >
<!ELEMENT fileLocation ( #PCDATA ) >
<!ELEMENT filename ( #PCDATA ) >

<!ELEMENT classes ( class+ ) >
<!ELEMENT class ( #PCDATA ) >

=== mithunmo/phpsample/data/config/bootstrap-core.xml
<!DOCTYPE config SYSTEM "../dtds/bootstrapConfig.dtd">
<bootstrap>
	<application>Scorpio Framework</application>
	<filename>bootstrap-core</filename>
	<fileLocation>temp</fileLocation>
	<classes>
		<class>baseSet</class>
		<class>baseOptionsSet</class>
		<class>baseTableParamSet</class>
		<class>baseObjectSet</class>
		<class>baseSearch</class>
		<class>baseSearchInterface</class>
		<class>baseResultSet</class>
		<class>systemDaoInterface</class>
		<class>systemDaoValidatorInterface</class>
		<class>system</class>
		<class>systemException</class>
		<class>systemAutoload</class>
		<class>systemAutoloadException</class>
		<class>systemConfigBase</class>
		<class>systemConfig</class>
		<class>systemConfigParam</class>
		<class>systemConfigParamSet</class>
		<class>systemConfigSection</class>
		<class>systemConfigException</class>
		<class>systemDateTime</class>
		<class>systemDateTimeZone</class>
		<class>systemDateEvent</class>
		<class>systemDateCalendar</class>
		<class>systemLocale</class>
		<class>systemEvent</class>
		<class>systemEventDispatcher</class>
		<class>systemLog</class>
		<class>systemLogException</class>
		<class>systemLogLevel</class>
		<class>systemLogFilter</class>
		<class>systemLogQueue</class>
		<class>systemLogSource</class>
		<class>systemLogWriter</class>
		<class>systemLogWriterFile</class>
		<class>systemRegistry</class>
		<class>systemRegistryException</class>
		<class>utilityStringFunction</class>
		<class>utilityXmlFunction</class>
		<class>dbManager</class>
		<class>dbOptions</class>
		<class>dbException</class>
	</classes>
</bootstrap>

=== mithunmo/phpsample/data/config/bootstrap-mvc.xml
<!DOCTYPE config SYSTEM "../dtds/bootstrapConfig.dtd">
<bootstrap>
	<application>Scorpio Framework</application>
	<filename>bootstrap-mvc</filename>
	<fileLocation>temp</fileLocation>
	<classes>
		<class>baseSet</class>
		<class>baseOptionsSet</class>
		<class>baseTableParamSet</class>
		<class>baseObjectSet</class>
		<class>baseSearch</class>
		<class>baseSearchInterface</class>
		<class>baseResultSet</class>
		<class>systemDaoInterface</class>
		<class>systemDaoValidatorInterface</class>
		<class>system</class>
		<class>systemException</class>
		<class>systemAutoload</class>
		<class>systemAutoloadException</class>
		<class>systemConfigBase</class>
		<class>systemConfig</class>
		<class>systemConfigParam</class>
		<class>systemConfigParamSet</class>
		<class>systemConfigSection</class>
		<class>systemConfigException</class>
		<class>systemDateTime</class>
		<class>systemDateTimeZone</class>
		<class>systemDateEvent</class>
		<class>systemDateCalendar</class>
		<class>systemLocale</class>
		<class>systemEvent</class>
		<class>systemEventDispatcher</class>
		<class>systemLog</class>
		<class>systemLogException</class>
		<class>systemLogLevel</class>
		<class>systemLogFilter</class>
		<class>systemLogQueue</class>
		<class>systemLogSource</class>
		<class>systemLogWriter</class>
		<class>systemLogWriterFile</class>
		<class>systemRegistry</class>
		<class>systemRegistryException</class>
		<class>utilityStringFunction</class>
		<class>utilityXmlFunction</class>
		<class>dbManager</class>
		<class>dbOptions</class>
		<class>dbException</class>
		<class>mvcSessionBase</class>
		<class>mvcAutoload</class>
		<class>mvcException</class>
		<class>mvcRequest</class>
		<class>mvcResponse</class>
		<class>mvcSiteConfig</class>
		<class>mvcSiteException</class>
		<class>mvcDistributorBase</class>
		<class>mvcDistributor</class>
		<class>mvcDistributorException</class>
		<class>mvcDistributorPluginSet</class>
		<class>mvcDistributorPlugin</class>
		<class>mvcDistributorPluginLog</class>
		<class>mvcDistributorPluginSession</class>
		<class>mvcDistributorPluginLocale</class>
		<class>mvcControllerBase</class>
		<class>mvcControllerMapper</class>
		<class>mvcControllerMap</class>
		<class>mvcControllerMapPath</class>
		<class>mvcControllerException</class>
		<class>mvcControllerAction</class>
		<class>mvcControllerActions</class>
		<class>mvcControllerViews</class>
		<class>mvcModelBase</class>
		<class>mvcModelException</class>
		<class>mvcViewBase</class>
		<class>mvcViewException</class>
		<class>mvcViewGeneric</class>
		<class>mvcViewHelperInterface</class>
		<class>mvcViewResource</class>
		<class>mvcViewCss</class>
		<class>mvcViewJavascript</class>
		<class>mvcViewEngineBase</class>
		<class>mvcViewEngineFactory</class>
		<class>mvcViewEngineGeneric</class>
		<class>mvcViewEnginePhp</class>
		<class>mvcViewEngineSmarty</class>
		<class>mvcViewHelperFactory</class>
		<class>mvcViewHelper</class>
		<class>utilityOutputWrapper</class>
		<class>utilityOutputWrapperArray</class>
		<class>utilityOutputWrapperIterator</class>
	</classes>
</bootstrap>
