=== mithunmo/phpsample/data/dtds/config.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT config ( section+ ) >

<!ELEMENT option EMPTY >
<!ATTLIST option name CDATA #REQUIRED >
<!ATTLIST option override CDATA #IMPLIED >
<!ATTLIST option value CDATA #REQUIRED >

<!ELEMENT section ( option+ ) >
<!ATTLIST section name CDATA #REQUIRED >
<!ATTLIST section override CDATA #REQUIRED >

=== mithunmo/phpsample/websites/mystage.mofilm.com/config.xml
<!DOCTYPE config SYSTEM "../../data/dtds/config.dtd">
<config>
	<section name="site" override="1">
		<option name="parent" value="my.mofilm.com" override="1" />
		<option name="active" value="1" override="1" />
		<option name="theme" value="mofilm" override="1" />
		<!-- Controls the individual sites log level, (integer) -->
		<option name="logLevel" value="16" override="1" />
		<option name="defaultController" value="account" override="1" />
	</section>
	<!-- If useCache is set to false (0), preloadSiteClasses MUST BE enabled -->
	<section name="autoload" override="1">
		<option name="useCache" value="1" override="1" />
		<option name="autoSave" value="1" override="1" />
		<option name="preloadSiteClasses" value="1" override="1" />
	</section>
	<section name="i18n" override="1">
		<option name="active" value="true" override="1" />
		<option name="identifier" value="t" override="1" />
		<option name="defaultLanguage" value="en" override="1" />
		<option name="adaptor" value="qt" override="1" />
		<option name="adaptorOptions" value="disableNotices=true|scan=directory" override="1" />
	</section>
</config>

=== mithunmo/phpsample/websites/mofilm.com/config.xml
<!DOCTYPE config SYSTEM "../../data/dtds/config.dtd">
<config>
	<section name="site" override="1">
		<option name="parent" value="base" override="1" />
		<option name="active" value="1" override="1" />
		<option name="theme" value="mofilm" override="1" />
		<option name="uriTextSeparator" value="-" override="1" />
		<option name="cacheStaticPages" value="1" override="1" />
		<option name="useCaptchaOnLoginForms" value="1" override="1" />
		<!-- Controls the individual sites log level, (integer) -->
		<option name="logLevel" value="32" override="1" />
		<option name="errorController" value="mofilmErrorController" />
	</section>
	<!-- If useCache is set to false (0), preloadSiteClasses MUST BE enabled -->
	<section name="autoload" override="1">
		<option name="useCache" value="1" override="1" />
		<option name="autoSave" value="1" override="1" />
		<option name="preloadSiteClasses" value="1" override="1" />
	</section>
	<section name="classes" override="1">
		<option name="mofilmErrorController" value="errorController.class.php" override="1" />
	</section>
	<section name="distributorPlugins" override="1">
		<option name="mvcDistributorPluginSession" value="true" override="1" />
		<option name="mvcDistributorPluginTranslate" value="true" override="1" />
		<option name="mvcDistributorPluginErrorHandler" value="true" override="1" />
	</section>
	<!-- internationalisation options, configure the adaptor and defaults per site -->
	<section name="i18n" override="1">
		<option name="active" value="true" />
		<option name="identifier" value="t" />
		<option name="defaultLanguage" value="en" />
		<option name="adaptor" value="qt" />
		<option name="adaptorOptions" value="disableNotices=true|scan=directory" />
	</section>
</config>
