=== mithunmo/phpsample/data/dtds/controllerMap.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT controller ( controllers? ) >
<!ATTLIST controller description CDATA #IMPLIED >
<!ATTLIST controller path CDATA #IMPLIED >
<!ATTLIST controller name CDATA #REQUIRED >

<!ELEMENT controllers ( controller+ ) >

=== mithunmo/phpsample/websites/mybcsff345.mofilm.cn/controllerMap.xml
<!DOCTYPE controllers SYSTEM "../../data/dtds/controllerMap.dtd">
<controllers>
	<controller name="home" />
	<!--<controller name="search" />-->
	<controller name="track" />
	<controller name="account">
		<controllers>
			<controller name="profile" path="/account/profileController.class.php" />
			<controller name="upload" path="/account/uploadController.class.php" />
			<controller name="pm" description="Private Messages" path="/account/pmController.class.php" />
			<controller name="review" description="Movie Review"/>
			<controller name="myVideo" description ="My Video"/>
			<controller name="grants" description="User Grants Details" />
		</controllers>
	</controller>
	
	<controller name="xml" />
	<controller name="video" />
	<controller name="watch" path="/video/videoController.class.php" />
	
	<controller name="user" />
	<controller name="u" path="/user/userController.class.php" />
	
	<!--<controller name="group" />
	<controller name="g" path="/group/groupController.class.php" />-->
	
	<controller name="download" />
	<controller name="captcha" />
	<controller name="uploadFiles" />
	<controller name="dl" path="/download/downloadController.class.php" />
	<controller name="brief" path="/download/downloadController.class.php" />
	<controller name="momusic" path="/momusic/momusicController.class.php" />
	<controller name="videoPlatform" description="platform" />
	<controller name="music" description="music" />
	<controller name="show" description="show" />
</controllers>
